site_name: Documentación Ren'py Español
site_description: Documentación de Ren'Py en Español

theme:
  name: material
  language: es
  logo: assets/renpy-logo.png
  favicon: assets/renpy.ico

  features:
    - navigation.sections
    - navigation.expand
    - toc.follow
    - search.highlight
    - search.suggest

  palette:
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Modo claro

    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Modo oscuro

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

extra:
  analytics:
    provider: google
    property: G-PQZ2KT1TZ5

nav:
  - Index: Index.md
  - Inicio Rápido: Inicio rápido.md
  - Herramientas para Desarrolladores: Herramientas para Desarrolladores.md
