site_name: Ren'Py Visual Novel Engine
site_description: Documentación de Ren'Py en Español

theme:
  name: material
  language: es

  features:
    - navigation.sections
    - navigation.expand
    - toc.follow
    - search.highlight
    - search.suggest

  palette:
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Modo claro

    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Modo oscuro